In [1]:
import numpy as np

In [95]:
a=np.random.randint(20,60,15)

In [97]:
a.ndim

1

In [99]:
a[4:12]

array([54, 36, 30, 46, 52, 32, 43, 28])

In [101]:
a[-2:-10:-1]

array([39, 52, 28, 43, 32, 52, 46, 30])

In [103]:
a

array([29, 39, 56, 27, 54, 36, 30, 46, 52, 32, 43, 28, 52, 39, 39])

In [105]:
a[a<30]

array([29, 27, 28])

In [107]:
np.where(a<30)

(array([ 0,  3, 11], dtype=int64),)

In [109]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [35]:
b[2] #2nd row

array([30, 41, 26, 21, 28, 29, 17, 38])

In [37]:
b[:,7] #7th column(starting from 0)

array([23, 18, 38, 35, 35, 47, 39])

In [47]:
b[3,1] #to access 47-3rd row and 1st column

47

In [49]:
b[6,4]

45

In [53]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])

In [57]:
b[1:5,1:4]

array([[29, 48, 25],
       [41, 26, 21],
       [47, 16, 15],
       [30, 25, 34]])

In [61]:
#array[row_start:row_end:row_step,column_start:column_end:column_step

In [63]:
b[3:6,2:6]

array([[16, 15, 48, 22],
       [25, 34, 42, 16],
       [21, 45, 37, 48]])

In [67]:
b[1:7,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [75]:
b[-6:-1]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47]])

In [87]:
# 41,28,38,30,42,35

In [117]:
b[2:5:2,1:8:3]

array([[41, 28, 38],
       [30, 42, 35]])

In [119]:
b[b>40]

array([44, 48, 47, 41, 49, 47, 48, 44, 42, 45, 45, 45, 48, 47, 45, 44])

In [113]:
np.where(b>40)#we use where() to access the element based on index

(array([0, 1, 1, 2, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 6, 6], dtype=int64),
 array([4, 2, 4, 1, 0, 1, 4, 6, 4, 0, 1, 3, 5, 7, 4, 6], dtype=int64))