In [13]:
import numpy as np
import pandas as pd
import seaborn as sns


In [20]:
k=[4,2.56789,9,87.9999,40]
k

[4, 2.56789, 9, 87.9999, 40]

In [24]:
pd.Series(k) #only for one dimensional data

0     4.00000
1     2.56789
2     9.00000
3    87.99990
4    40.00000
dtype: float64

In [45]:
a=np.random.randint(20,50,15)
a

array([38, 48, 40, 39, 20, 25, 44, 25, 42, 25, 38, 38, 22, 38, 37])

In [47]:
a.ndim #dimension

1

In [49]:
pd.Series(a)

0     38
1     48
2     40
3     39
4     20
5     25
6     44
7     25
8     42
9     25
10    38
11    38
12    22
13    38
14    37
dtype: int32

In [51]:
a[0]

38

In [53]:
a[2:5]

array([40, 39, 20])

In [55]:
s=pd.Series(a)
a

array([38, 48, 40, 39, 20, 25, 44, 25, 42, 25, 38, 38, 22, 38, 37])

In [57]:
s

0     38
1     48
2     40
3     39
4     20
5     25
6     44
7     25
8     42
9     25
10    38
11    38
12    22
13    38
14    37
dtype: int32

In [59]:
s[4:10]

4    20
5    25
6    44
7    25
8    42
9    25
dtype: int32

In [71]:
np.random.seed(34)
b=np.random.randint(100,200,(6,5))

In [73]:
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [75]:
b.ndim

2

In [77]:
b.shape

(6, 5)

In [113]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'])
df

Roll  name  age  adds  country
0   133   185  168   135      169
1   111   178  129   118      129
2   189   129  120   196      162
3   105   120  151   119      185
4   121   163  172   142      184
5   172   177  136   102      137

In [115]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'],index=[182,183,185,186,187,188])
df

Roll  name  age  adds  country
182   133   185  168   135      169
183   111   178  129   118      129
185   189   129  120   196      162
186   105   120  151   119      185
187   121   163  172   142      184
188   172   177  136   102      137

In [117]:
df.iloc[0] #gives default values

Roll       133
name       185
age        168
adds       135
country    169
Name: 182, dtype: int32

In [119]:
df.loc[182] #takes actual row num and column number

Roll       133
name       185
age        168
adds       135
country    169
Name: 182, dtype: int32

In [121]:
df.iloc[0,0]

133

In [123]:
df.loc[182,'Roll']

133

In [125]:
df.loc[182,['Roll','name','age']]

Roll    133
name    185
age     168
Name: 182, dtype: int32

In [127]:
df.iloc[0,0:3]

Roll    133
name    185
age     168
Name: 182, dtype: int32

In [109]:
df.iloc[0,[0,1,2]]

Roll    133
name    185
age     168
Name: 182, dtype: int32

In [129]:
df.iloc[[1,3,4]]

Roll  name  age  adds  country
183   111   178  129   118      129
186   105   120  151   119      185
187   121   163  172   142      184

In [131]:
df.age

182    168
183    129
185    120
186    151
187    172
188    136
Name: age, dtype: int32

In [141]:
df['age'] #to access single column

182    168
183    129
185    120
186    151
187    172
188    136
Name: age, dtype: int32

In [143]:
df[['age','adds']]  #whenever we want to access multiple columns we need to write in double brackets

age  adds
182  168   135
183  129   118
185  120   196
186  151   119
187  172   142
188  136   102

In [147]:
#to access specific rows(loc)
df.loc[[182,185,186],['adds','name','Roll']]

adds  name  Roll
182   135   185   133
185   196   129   189
186   119   120   105

In [149]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [151]:
sns.load_dataset('anagrams') #we can access any dataset

subidr    attnr  num1  num2  num3
0        1  divided     2   4.0     7
1        2  divided     3   4.0     5
2        3  divided     3   5.0     6
3        4  divided     5   7.0     5
4        5  divided     4   5.0     8
5        6  divided     5   5.0     6
6        7  divided     5   4.5     6
7        8  divided     5   7.0     8
8        9  divided     2   3.0     7
9       10  divided     6   5.0     6
10      11  focused     6   5.0     6
11      12  focused     8   9.0     8
12      13  focused     6   5.0     9
13      14  focused     8   8.0     7
14      15  focused     8   8.0     7
15      16  focused     6   8.0     7
16      17  focused     7   7.0     6
17      18  focused     7   8.0     6
18      19  focused     5   6.0     6
19      20  focused     6   6.0     5

In [153]:
type(df)

pandas.core.frame.DataFrame

In [155]:
df.shape

(6, 5)

In [157]:
df.columns

Index(['Roll', 'name', 'age', 'adds', 'country'], dtype='object')