In [1]:
import numpy as np

In [3]:
j=[4,6,2,8,9,1]
j

[4, 6, 2, 8, 9, 1]

In [5]:
np.array(j)

array([4, 6, 2, 8, 9, 1])

In [7]:
tuple(j)

(4, 6, 2, 8, 9, 1)

In [9]:
d=np.array(j)

In [11]:
d

array([4, 6, 2, 8, 9, 1])

In [13]:
d.ndim

1

In [15]:
d.shape

(6,)

In [17]:
w=d.reshape(2,3)

In [19]:
w

array([[4, 6, 2],
       [8, 9, 1]])

In [21]:
d.size

6

In [23]:
s=[[1,2,3,4],[5,6,7,8],[9,0,11,12],[13,14,15,16],[17,18,19,20]]
s

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 0, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20]]

In [25]:
arr1=np.array(s)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
arr1.shape

(5, 4)

In [29]:
arr1.size

20

In [31]:
arr1.ndim

2

In [33]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [35]:
z=arr1.reshape(20,1)
z

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 0],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [37]:
range(5, 20)

range(5, 20)

In [39]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [41]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [43]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [45]:
range(5,50,5)

range(5, 50, 5)

In [47]:
j=[10,20,30,40,50,60,70,80,90]
j

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [49]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])
        print(x)
        print(y)

[10]
[20]
[10, 30]
[20, 40]
[10, 30, 50]
[20, 40, 60]
[10, 30, 50, 70]
[20, 40, 60, 80]
